apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-a2du
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-a2du
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-a2du
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-a2du
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-a2du
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wuvv-tenant/nodejs-users/simple-nodejs-app-a2du@sha256:4306a8bc7e0cb6b2f2037e23586579eebca54500c557b99dce3602c44ab0ad1e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
